import { z } from "zod";

export type State = z.infer<typeof StateSchema>["data"][number];

export const StateSchema = z.object({
  success: z.boolean(),
  request_time: z.number(),
  data: z.array(
    z.object({
      wards: z.array(
        z.object({
          status: z.string(),
          _id: z.string(),
          state_id: z.number(),
          state: z.string(),
          lga_id: z.number(),
          lga: z.string(),
          state_constituency_id: z.number(),
          state_constituency: z.string(),
          federal_constituency_id: z.number(),
          federal_constituency: z.string(),
          senatorial_district_id: z.number(),
          senatorial_district: z.string(),
          name: z.string(),
          code: z.string(),
          old_name: z.string(),
          ward_id: z.number(),
          created_at: z.string(),
          updated_at: z.string(),
          __v: z.number(),
        })
      ),
      election_wards: z.array(z.unknown()),
      status: z.string(),
      is_mapped: z.boolean(),
      _id: z.string(),
      lga: z.object({
        status: z.string(),
        _id: z.string(),
        state_id: z.number(),
        state: z.string(),
        name: z.string(),
        code: z.string(),
        lga_id: z.number(),
        created_at: z.string(),
        updated_at: z.string(),
        __v: z.number(),
      }),
      election: z.object({
        status: z.string(),
        version: z.number(),
        is_mapped: z.boolean(),
        _id: z.string(),
        full_name: z.string(),
        election_id: z.number(),
        domain_id: z.number(),
        domain_type: z.string(),
        election_type_id: z.number(),
        state_id: z.number(),
        state: z.string(),
        election_date: z.string(),
        domain: z.string(),
        election_type: z.string(),
        onModel: z.string(),
        created_at: z.string(),
        updated_at: z.string(),
        __v: z.number(),
      }),
      election_id: z.number(),
      state: z.object({
        status: z.string(),
        _id: z.string(),
        presidential_id: z.number(),
        presidential: z.string(),
        name: z.string(),
        code: z.string(),
        state_id: z.number(),
        created_at: z.string(),
        updated_at: z.string(),
        __v: z.number(),
      }),
      created_at: z.string(),
      updated_at: z.string(),
      __v: z.number(),
    })
  ),
});

export type PollingUnit = z.infer<typeof PollingUnitSchema>["data"][number];
export const PollingUnitSchema = z.object({
  success: z.boolean(),
  request_time: z.number(),
  data: z.array(
    z.object({
      status: z.string(),
      _id: z.string(),
      polling_unit_id: z.number(),
      polling_unit: z.object({
        status: z.string(),
        generation: z.number(),
        db_generation: z.number(),
        is_accredited: z.number(),
        _id: z.string(),
        state_id: z.number(),
        state: z.string(),
        lga_id: z.number(),
        ward_id: z.number(),
        state_constituency_id: z.number(),
        state_constituency: z.string(),
        federal_constituency_id: z.number(),
        federal_constituency: z.string(),
        senatorial_district_id: z.number(),
        senatorial_district: z.string(),
        name: z.string(),
        code: z.string(),
        pu_code: z.string(),
        old_name: z.string(),
        polling_unit_id: z.number(),
        created_at: z.string(),
        updated_at: z.string(),
        __v: z.number(),
        pu_code_string: z.string(),
      }),
      name: z.string(),
      code: z.string(),
      pu_code: z.string(),
      ward_id: z.number(),
      lga_id: z.number(),
      lga: z.string(),
      created_at: z.string(),
      updated_at: z.string(),
      __v: z.number(),
      document: z.object({
        external: z.boolean(),
        status: z.number(),
        _id: z.string(),
        url: z.string(),
        size: z.number(),
        updated_at: z.string(),
      }).optional().nullable(),
      document_id: z.number().optional(),
      old_documents: z.array(z.unknown()).optional(),
      session: z.string().optional(),
    })
  ),
});

export type Ward = z.infer<typeof WardSchema>;
export const WardSchema = z.object({
  status: z.string(),
  _id: z.string(),
  state_id: z.number(),
  state: z.string(),
  state_name: z.string(),
  lga_id: z.number(),
  lga: z.string(),
  lga_name: z.string(),
  state_constituency_id: z.number(),
  state_constituency: z.string(),
  federal_constituency_id: z.number(),
  federal_constituency: z.string(),
  senatorial_district_id: z.number(),
  senatorial_district: z.string(),
  name: z.string(),
  code: z.string(),
  old_name: z.string(),
  ward_id: z.number(),
  created_at: z.string(),
  updated_at: z.string(),
  __v: z.number(),
});
